from __future__ import annotations

from technitium_dns_mcp.client.models import (
    ConfirmationMode,
    ConfirmationPolicy,
    EndpointClassification,
    EndpointMetadata,
)


def _endpoint(
    tool_name: str,
    api_path: str,
    family: str,
    classification: EndpointClassification,
    *,
    required_params: tuple[str, ...] = (),
    optional_params: tuple[str, ...] = (),
    confirmation_mode: ConfirmationMode = "none",
    acknowledgement: str | None = None,
) -> EndpointMetadata:
    return EndpointMetadata(
        tool_name=tool_name,
        api_path=api_path,
        family=family,
        classification=classification,
        required_params=required_params,
        optional_params=optional_params,
        confirmation_policy=ConfirmationPolicy(
            mode=confirmation_mode,
            acknowledgement=acknowledgement,
        ),
    )


ENDPOINT_CATALOG: tuple[EndpointMetadata, ...] = (
    _endpoint("dns_get_settings", "/api/settings/get", "settings", "readonly"),
    _endpoint(
        "dns_get_top_stats",
        "/api/dashboard/stats/getTop",
        "dashboard",
        "readonly",
        required_params=("type", "statsType"),
        optional_params=(
            "limit",
            "start",
            "end",
            "noReverseLookup",
            "onlyRateLimitedClients",
            "node",
        ),
    ),
    _endpoint(
        "dns_delete_all_stats",
        "/api/dashboard/stats/deleteAll",
        "dashboard",
        "destructive",
        confirmation_mode="destructive",
    ),
    _endpoint("dns_list_zones", "/api/zones/list", "zones", "readonly"),
    _endpoint("dns_list_catalog_zones", "/api/zones/catalogs/list", "zones", "readonly"),
    _endpoint(
        "dns_get_zone_options",
        "/api/zones/options/get",
        "zones",
        "readonly",
        required_params=("zone",),
        optional_params=(
            "includeAvailableCatalogZoneNames",
            "includeAvailableTsigKeyNames",
        ),
    ),
    _endpoint(
        "dns_set_zone_options",
        "/api/zones/options/set",
        "zones",
        "mutation",
        required_params=("zone",),
        confirmation_mode="confirm",
    ),
    _endpoint(
        "dns_get_zone_permissions",
        "/api/zones/permissions/get",
        "zones",
        "readonly",
        required_params=("zone",),
        optional_params=("includeUsersAndGroups",),
    ),
    _endpoint(
        "dns_set_zone_permissions",
        "/api/zones/permissions/set",
        "zones",
        "mutation",
        required_params=("zone",),
        optional_params=("userPermissions", "groupPermissions"),
        confirmation_mode="confirm",
    ),
    _endpoint(
        "dns_create_primary_zone",
        "/api/zones/create",
        "zones",
        "mutation",
        required_params=("zone",),
        confirmation_mode="confirm",
    ),
    _endpoint(
        "dns_create_zone",
        "/api/zones/create",
        "zones",
        "mutation",
        required_params=("zone", "type"),
        confirmation_mode="confirm",
    ),
    _endpoint(
        "dns_clone_zone",
        "/api/zones/clone",
        "zones",
        "mutation",
        required_params=("zone", "sourceZone"),
        confirmation_mode="confirm",
    ),
    _endpoint(
        "dns_convert_zone",
        "/api/zones/convert",
        "zones",
        "mutation",
        required_params=("zone", "type"),
        confirmation_mode="confirm",
    ),
    _endpoint(
        "dns_enable_zone",
        "/api/zones/enable",
        "zones",
        "mutation",
        required_params=("zone",),
        confirmation_mode="confirm",
    ),
    _endpoint(
        "dns_disable_zone",
        "/api/zones/disable",
        "zones",
        "mutation",
        required_params=("zone",),
        confirmation_mode="confirm",
    ),
    _endpoint(
        "dns_delete_zone",
        "/api/zones/delete",
        "zones",
        "destructive",
        required_params=("zone",),
        confirmation_mode="destructive",
    ),
    _endpoint(
        "dns_resync_zone",
        "/api/zones/resync",
        "zones",
        "mutation",
        required_params=("zone",),
        confirmation_mode="confirm",
    ),
    _endpoint(
        "dns_get_zone_ds_info",
        "/api/zones/dnssec/viewDS",
        "dnssec",
        "readonly",
        required_params=("zone",),
    ),
    _endpoint(
        "dns_get_zone_dnssec_properties",
        "/api/zones/dnssec/properties/get",
        "dnssec",
        "readonly",
        required_params=("zone",),
    ),
    _endpoint(
        "dns_sign_zone",
        "/api/zones/dnssec/sign",
        "dnssec",
        "mutation",
        required_params=("zone",),
        confirmation_mode="confirm",
    ),
    _endpoint(
        "dns_unsign_zone",
        "/api/zones/dnssec/unsign",
        "dnssec",
        "destructive",
        required_params=("zone",),
        confirmation_mode="destructive",
    ),
    _endpoint(
        "dns_convert_zone_to_nsec",
        "/api/zones/dnssec/properties/convertToNSEC",
        "dnssec",
        "mutation",
        required_params=("zone",),
        confirmation_mode="confirm",
    ),
    _endpoint(
        "dns_convert_zone_to_nsec3",
        "/api/zones/dnssec/properties/convertToNSEC3",
        "dnssec",
        "mutation",
        required_params=("zone", "iterations", "saltLength"),
        confirmation_mode="confirm",
    ),
    _endpoint(
        "dns_update_zone_nsec3_parameters",
        "/api/zones/dnssec/properties/updateNSEC3Params",
        "dnssec",
        "mutation",
        required_params=("zone", "iterations", "saltLength"),
        confirmation_mode="confirm",
    ),
    _endpoint(
        "dns_update_zone_dnskey_ttl",
        "/api/zones/dnssec/properties/updateDnsKeyTtl",
        "dnssec",
        "mutation",
        required_params=("zone", "dnsKeyTtl"),
        confirmation_mode="confirm",
    ),
    _endpoint(
        "dns_add_zone_private_key",
        "/api/zones/dnssec/properties/addPrivateKey",
        "dnssec",
        "mutation",
        required_params=("zone",),
        confirmation_mode="confirm",
    ),
    _endpoint(
        "dns_update_zone_private_key",
        "/api/zones/dnssec/properties/updatePrivateKey",
        "dnssec",
        "mutation",
        required_params=("zone", "keyTag", "rolloverDays"),
        confirmation_mode="confirm",
    ),
    _endpoint(
        "dns_delete_zone_private_key",
        "/api/zones/dnssec/properties/deletePrivateKey",
        "dnssec",
        "destructive",
        required_params=("zone", "keyTag"),
        confirmation_mode="destructive",
    ),
    _endpoint(
        "dns_publish_all_zone_private_keys",
        "/api/zones/dnssec/properties/publishAllPrivateKeys",
        "dnssec",
        "mutation",
        required_params=("zone",),
        confirmation_mode="confirm",
    ),
    _endpoint(
        "dns_rollover_zone_dnskey",
        "/api/zones/dnssec/properties/rolloverDnsKey",
        "dnssec",
        "mutation",
        required_params=("zone", "keyTag"),
        confirmation_mode="confirm",
    ),
    _endpoint(
        "dns_retire_zone_dnskey",
        "/api/zones/dnssec/properties/retireDnsKey",
        "dnssec",
        "mutation",
        required_params=("zone", "keyTag"),
        confirmation_mode="confirm",
    ),
    _endpoint(
        "dns_get_records",
        "/api/zones/records/get",
        "records",
        "readonly",
        required_params=("domain",),
        optional_params=("zone", "listZone"),
    ),
    _endpoint(
        "dns_add_record",
        "/api/zones/records/add",
        "records",
        "mutation",
        required_params=("domain",),
        optional_params=("zone", "type", "ttl", "overwrite", "comments", "expiryTtl"),
        confirmation_mode="confirm",
    ),
    _endpoint(
        "dns_update_record",
        "/api/zones/records/update",
        "records",
        "mutation",
        required_params=("domain",),
        optional_params=(
            "zone",
            "type",
            "newDomain",
            "ttl",
            "disable",
            "comments",
            "expiryTtl",
        ),
        confirmation_mode="confirm",
    ),
    _endpoint(
        "dns_delete_record",
        "/api/zones/records/delete",
        "records",
        "destructive",
        required_params=("domain",),
        optional_params=("zone", "type"),
        confirmation_mode="destructive",
    ),
    _endpoint("dns_list_cache", "/api/cache/list", "cache", "readonly"),
    _endpoint(
        "dns_delete_cached_zone",
        "/api/cache/delete",
        "cache",
        "destructive",
        required_params=("domain",),
        confirmation_mode="destructive",
    ),
    _endpoint(
        "dns_flush_cache",
        "/api/cache/flush",
        "cache",
        "destructive",
        confirmation_mode="destructive",
    ),
    _endpoint("dns_list_allowed_zones", "/api/allowed/list", "allowed", "readonly"),
    _endpoint("dns_export_allowed_zones", "/api/allowed/export", "allowed", "readonly"),
    _endpoint(
        "dns_add_allowed_zone",
        "/api/allowed/add",
        "allowed",
        "mutation",
        required_params=("domain",),
        confirmation_mode="confirm",
    ),
    _endpoint(
        "dns_delete_allowed_zone",
        "/api/allowed/delete",
        "allowed",
        "destructive",
        required_params=("domain",),
        confirmation_mode="destructive",
    ),
    _endpoint(
        "dns_flush_allowed_zones",
        "/api/allowed/flush",
        "allowed",
        "destructive",
        confirmation_mode="destructive",
    ),
    _endpoint(
        "dns_import_allowed_zones",
        "/api/allowed/import",
        "allowed",
        "mutation",
        required_params=("allowedZones",),
        confirmation_mode="confirm",
    ),
    _endpoint("dns_list_blocked_zones", "/api/blocked/list", "blocked", "readonly"),
    _endpoint("dns_export_blocked_zones", "/api/blocked/export", "blocked", "readonly"),
    _endpoint(
        "dns_add_blocked_zone",
        "/api/blocked/add",
        "blocked",
        "mutation",
        required_params=("domain",),
        confirmation_mode="confirm",
    ),
    _endpoint(
        "dns_delete_blocked_zone",
        "/api/blocked/delete",
        "blocked",
        "destructive",
        required_params=("domain",),
        confirmation_mode="destructive",
    ),
    _endpoint(
        "dns_flush_blocked_zones",
        "/api/blocked/flush",
        "blocked",
        "destructive",
        confirmation_mode="destructive",
    ),
    _endpoint(
        "dns_import_blocked_zones",
        "/api/blocked/import",
        "blocked",
        "mutation",
        required_params=("blockedZones",),
        confirmation_mode="confirm",
    ),
    _endpoint("dns_list_apps", "/api/apps/list", "apps", "readonly"),
    _endpoint("dns_list_store_apps", "/api/apps/listStoreApps", "apps", "readonly"),
    _endpoint(
        "dns_get_app_config",
        "/api/apps/config/get",
        "apps",
        "readonly",
        required_params=("name",),
    ),
    _endpoint(
        "dns_download_and_install_app",
        "/api/apps/downloadAndInstall",
        "apps",
        "mutation",
        required_params=("name", "url"),
        confirmation_mode="confirm",
    ),
    _endpoint(
        "dns_download_and_update_app",
        "/api/apps/downloadAndUpdate",
        "apps",
        "mutation",
        required_params=("name", "url"),
        confirmation_mode="confirm",
    ),
    _endpoint(
        "dns_install_app",
        "/api/apps/install",
        "apps",
        "mutation",
        required_params=("name",),
        confirmation_mode="confirm",
    ),
    _endpoint(
        "dns_update_app",
        "/api/apps/update",
        "apps",
        "mutation",
        required_params=("name",),
        confirmation_mode="confirm",
    ),
    _endpoint(
        "dns_uninstall_app",
        "/api/apps/uninstall",
        "apps",
        "destructive",
        required_params=("name",),
        confirmation_mode="destructive",
    ),
    _endpoint(
        "dns_set_app_config",
        "/api/apps/config/set",
        "apps",
        "mutation",
        required_params=("name", "config"),
        confirmation_mode="confirm",
    ),
    _endpoint(
        "dns_resolve_query",
        "/api/dnsClient/resolve",
        "dns_client",
        "readonly",
        required_params=("server", "domain", "type"),
        optional_params=("protocol", "dnssec", "eDnsClientSubnet"),
    ),
    _endpoint(
        "dns_get_tsig_key_names",
        "/api/settings/getTsigKeyNames",
        "settings",
        "readonly",
    ),
    _endpoint(
        "dns_set_settings",
        "/api/settings/set",
        "settings",
        "mutation",
        confirmation_mode="confirm",
    ),
    _endpoint(
        "dns_force_update_block_lists",
        "/api/settings/forceUpdateBlockLists",
        "settings",
        "mutation",
        confirmation_mode="confirm",
    ),
    _endpoint(
        "dns_temporary_disable_blocking",
        "/api/settings/temporaryDisableBlocking",
        "settings",
        "mutation",
        required_params=("minutes",),
        confirmation_mode="confirm",
    ),
    _endpoint(
        "dns_backup_settings",
        "/api/settings/backup",
        "settings",
        "admin",
        confirmation_mode="critical",
        acknowledgement="backup-settings",
    ),
    _endpoint(
        "dns_restore_settings",
        "/api/settings/restore",
        "settings",
        "admin",
        confirmation_mode="critical",
        acknowledgement="restore-settings",
    ),
)

_ENDPOINTS_BY_TOOL = {endpoint.tool_name: endpoint for endpoint in ENDPOINT_CATALOG}


def get_endpoint(tool_name: str) -> EndpointMetadata:
    try:
        return _ENDPOINTS_BY_TOOL[tool_name]
    except KeyError as exc:
        raise KeyError(f"Unknown MCP tool in endpoint catalog: {tool_name}") from exc


def list_endpoints(
    *,
    family: str | None = None,
    classification: EndpointClassification | None = None,
) -> tuple[EndpointMetadata, ...]:
    return tuple(
        endpoint
        for endpoint in ENDPOINT_CATALOG
        if (family is None or endpoint.family == family)
        and (classification is None or endpoint.classification == classification)
    )
